### ISSUE TITLE
Não está marcando o chat como lido 

### ISSUE THREAD

**Issue by mazzucco-br** [ebenezerIt/chat-dos-politicos#47]
Ao entrar com id na URL, ou fazer reload, o usuário selecionado não é marcado como lido no sidebar

**Comment by mazzucco-br** [comment]
@Sarahbarros Confirme se esse erro foi corrigido

**Comment by Sarahbarros** [comment]
@mazzucco-br  sim o erro foi corrigido , porém quando da o reload muda pra página 404.
