### ISSUE TITLE
Corrigir formatação da ultima mensagem no sidebar

### ISSUE THREAD

**Issue by mazzucco-br** [ebenezerIt/chat-dos-politicos#9]
Dependendo do tamanho da janela o layout perde a formatação quando a ultima mensagem possui um texto grande
- Adicionar elipse (...) conforme whatappweb 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_image_text

**Comment by anamazzucco** [comment]
Foi resolvida
